### ISSUE TITLE
Plugins are unable to see the Parallels private IP

### ISSUE THREAD

**Issue by wizonesolutions** [Parallels/vagrant-parallels#167]
e.g. https://github.com/smdahlen/vagrant-hostmanager/issues/129#issuecomment-69016345

Is the IP address Parallels Desktop assigns to machines not the same as a `config.vm.network "private_network", ip: "192.168.33.10"`-type configuration? Is this by design?

**Comment by legal90** [comment]
> Is the IP address Parallels Desktop assigns to machines not the same as a config.vm.network "private_network", ip: "192.168.33.10"-type configuration?

By default virtual machine in Parallels Desktop has the only one network interface - `Shared` and by default it uses network range "10.211.55.0/24"
And it doesn't have anything common with `private_network` configuration in Vagrant.

@wizonesolutions Could you please explain, what the problem is and how to reproduce it?

**Comment by wizonesolutions** [comment]
@legal90 OK, I will check if this is still happening. I wonder if it was a configuration issue because I have seen the aliases (from the plugin) in `/etc/hosts` now. But they might have been put there from when I was testing with a different hypervisor, so I will check.

**Comment by wizonesolutions** [comment]
Don't know what caused this, but it is definitely working fine now! Closing.
