### ISSUE TITLE
Parallels driver does not port forward 'ssh' config for Parallels Desktop 10+

### ISSUE THREAD

**Issue by mefellows** [Parallels/vagrant-parallels#168]
As per the comment in the [compile_forwarded_ports.rb](https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/util/compile_forwarded_ports.rb#L29) file, you need to manually set the ssh port in a block similar to as it currently skips the default `ssh` configuration:

```
  config.vm.provider "parallels" do |v|
    config.vm.box = "packer-parallels"
    config.ssh.host = "127.0.0.1"
    config.ssh.guest_port = 2223
    config.vm.network "forwarded_port", guest: 22, host: 2223
  end
```
Now that Parallels Desktop 10 is available, we should be able to query the version and follow the appropriate behaviour, reducing non-standard, boilerplate configuration.

**Comment by legal90** [comment]
https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/util/compile_forwarded_ports.rb#L29 <- This line has been added to completely prevent a ssh configuration over the forwarded port and use a direct IP connection instead. It was caused by a bug in early Parallels Desktop 10 release: GH-146.

@mefellows Do you mean that you still want to use forwarded port for that by some reason? 

Anyway, there is no reason for an additional version checking here, because port forwarding is implemented only for Parallels Desktop >= 10. 
E.q. this line is just ignored (no effect) with Parallels Desktop 8 and 9:
```
config.vm.network "forwarded_port", guest: 22, host: 2223
```

**Comment by legal90** [comment]
Please, describe your use case and the issue you've faced.

**Comment by mefellows** [comment]
Thanks @legal90, I will strip down the project I was working on into its bare bones and see if there is indeed a use-case/issue at all. I now believe it may have been a configuration issue with Virtualbox that was flowing into the Parallels builder.

Either way - should the #TODO be removed now that it's redundant?

**Comment by legal90** [comment]
@mefellows OK, I've just deleted this TODO comment
