### ISSUE TITLE
Enable default of prlctl set VMNAME --on-window-close keep-running

### ISSUE THREAD

**Issue by modest** [Parallels/vagrant-parallels#182]
Vagrant boxes are often intended to be headless.  If the Parallels app is open, each Vagrant VM will open as a GUI window.  If that window is closed, the Parallels UI forces the user to decide between halting or suspending the VM.

For parity with VirtualBox, the default behavior should be to set $ prlctrl set VMNAME --on-window-close keep-running    for new VMs.  This will allow the user to close the GUI window without impacting the Vagrant VM.

**Comment by legal90** [comment]
It looks reasonable and I want to implement it in the scope of upcoming refactoring of the default settings in `vagrant-parallels`. 

But I'd like to notice that this option, `--on-window-close keep-running` is already applied by default to all our official boxes (https://atlas.hashicorp.com/parallels). It happens because Packer utility, which we use to build our boxes, sets this option to the virtual machine by default:
https://github.com/mitchellh/packer/blob/f7af571cd95718204c286b53588bffd5bd12e634/builder/parallels/common/driver_10.go#L15

**Comment by legal90** [comment]
Implemented in [v1.5.0](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.5.0)
Option `--on-window-close` is set to `keep-running` for Parallels Desktop >= 9
