### ISSUE TITLE
Guest IP doesn't get resolved if first network interface is not Shared

### ISSUE THREAD

**Issue by alh84001** [Parallels/vagrant-parallels#185]
Now I know this goes contrary to all the docs, but unfortunately I have a requirement which I can't get around of, where I must have a bridged adapter defined as the first guest network adapter. This causes the guest IP to never be resolved even if I add Shared network as a second adapter. I have this successfully running with VirtualBox so it would be nice to have it supported in Parallels as well.

The root cause is in the VagrantPlugins::Parallels:Driver:PD_8.read_mac_address which takes the first adapter MAC which it assumes belongs to the Shared network adapter and which is later used to look into Parallels DHCP leases to get the IP. However, bridged adapters don't get IP address assigned from Parallels, and their IP won't be listed there.

The fix with the least impact to any existing code out there would be to filter out any bridge MACs (e.g. prlctl ..... --info) before returning the first one.

**Comment by legal90** [comment]
It is really strange case :)
@alh84001 How do you change the type and order of network interfaces? Are you doing it manually, after the first `vagrant up`?

**Comment by alh84001** [comment]
Tell me about it :)

I redefine the first adapter and add shared network with provider customizations. I could then forward any ports using prlctl as well. But since I don't need to forward any ports I think that DHCP private network would ork equally as well.

Example (this is inside the provider config block):

```ruby
    config.vm.provider :parallels do |prl, config_override|
      config_override.vm.network :public_network, adapter: 0
      # on of the two bellow
      prl.customize ["set", :id, "--device-add", "net", "--type", "shared"]
      config_override.vm.network :private_network
    end

**Comment by legal90** [comment]
I've added the workaround for cases like yours in [v1.3.13](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.3.13). Now MAC of "Shared" adapter will be properly detected even if it is not the first.

But please be aware that such adapter re-ordering is not a supported case, because Vagrant configures only `private_network` and `private_network` interfaces in the guest OS. It means that if you move "Shared" to some other place, you will have to configure it from the guest side manually (or use custom pre-configured boxes). Otherwise, you will get "virtual machine boot timeout"

P.s. So, if you really need this trick, you can use these lines in Vagrantfile instead of mentioned above: 
```ruby
    config.vm.provider :parallels do |prl, config_override|
      config_override.vm.network :public_network, adapter: 0
      prl.network_adapter(1, :shared)
    end
```

**Comment by alh84001** [comment]
Sorry for the late reply, saw it before, but stuff got in the way.

Many, many thanks for adding the option.
