### ISSUE TITLE
vagrant halt not detecting machine shutdown

### ISSUE THREAD

**Issue by jfilip** [Parallels/vagrant-parallels#240]
I've recently encountered an issue where running `vagrant halt` will successfully shut the VM down but not detect that the VM has stopped and wait indefinitely until aborted.

See debug logs for `vagrant up` and `vagrant halt` here: https://gist.github.com/jfilip/458f269d28928c24c926

* Host OS: **Mac OS X 10.11.2**
* Guest OS: **Debian 8.1 x64**
* **Vagrant 1.8.1**
* **Parallels 11.1.2 (32408)**
* **parallels-guest 1.6.0**

And a GIF of the problem in action. Note that the halt command continues to wait even after Parallels Desktop clearly shows the VM is no longer running:

![vagrant_parallels_issue](https://cloud.githubusercontent.com/assets/845360/12106610/45203884-b32f-11e5-9a89-a269c1c01159.gif)

**Comment by legal90** [comment]
@jfilip Thanks for pointing on this! However, the root of this issue is on the Vagrant side, so there is nothing to fix in the provider.

I found the similar issue: https://github.com/mitchellh/vagrant/issues/6207
And declined PR: https://github.com/mitchellh/vagrant/pull/5280

And I've asked @sethvargo to assist, let's wait for response: https://github.com/mitchellh/vagrant/issues/6207#issuecomment-168972413

**Comment by jfilip** [comment]
@legal90 thanks for the reply. I'll follow the main vagrant issue as well.

**Comment by legal90** [comment]
I close this issue in favor of mitchellh/vagrant#6207, which has been just reopened.
