### ISSUE TITLE
Vagrant suspend or halt doesnt work

### ISSUE THREAD

**Issue by tosbaha** [Parallels/vagrant-parallels#248]
I am trying to use dokku

> git clone git@github.com:progrium/dokku.git
> cd dokku
> vagrant up --provider=parallels

I can only up the machine with vagrant up --provider=parallels. If I don't supply provider flag, I get

> 
> The "VBoxManage" command or one of its dependencies could not
> be found. Please verify VirtualBox is properly installed. You can verify
> everything is okay by running "VBoxManage --version" and verifying
> that the VirtualBox version is outputted.
> 
> If you're on Windows and just installed VirtualBox, you have to
> log out and log back in for the new environmental variables to take
> effect. If you're on Linux or Mac, verify your PATH contains the folder
> that has VBoxManage in it.

I can't halt the machine I tried 

vagrant halt --provider=parallels 

> An invalid option was specified. The help for this command
> is available below.
> 
> Usage: vagrant halt [options] [name]
> 
> Options:
> 
>     -f, --force                      Force shut down (equivalent of pulling power)
>     -h, --help                       Print this help

**Comment by legal90** [comment]
Hi @tosbaha 
You should just run `vagrant halt` without --provider flag.

https://www.vagrantup.com/docs/providers/basic_usage.html
> If you specified a `--provider` flag, you only need to do this for the `up` command. Once a machine is up and running, Vagrant is able to see what provider is backing a running machine, so commands such as `destroy`, `suspend`, etc. do not need to be told what provider to use.

**Comment by tosbaha** [comment]
Hi @legal90 
As I said using halt without provider flag also didn't work. It was looking for Virtualbox provider as you can see from the logs. Only way I made it work is by adding   
    
    config.vm.provider "parallels" do |prl|
        prl.memory = BOX_MEMORY # 1024
      end

block to my Vagrant file.  Because original Vagrant file doesn't have parallels provider.

**Comment by legal90** [comment]
Hm... That's weird and I can't reproduce it.
@tosbaha Please, reproduce this issue again with grabbing a debug log:
```
vagrant halt --debug 2>./debug.log
```

Then please share the debug log via something like Gist or Pastebin, or send it to me by e-mail (in the profile)

**Comment by tosbaha** [comment]
I am using the dokku's vagrant file. If you try 

> 
> git clone git@github.com:progrium/dokku.git
> cd dokku
> vagrant up

You will see that 

> 
> The "VBoxManage" command or one of its dependencies could not
> be found. Please verify VirtualBox is properly installed. You can verify
> everything is okay by running "VBoxManage --version" and verifying
> that the VirtualBox version is outputted.
> 
> If you're on Windows and just installed VirtualBox, you have to
> log out and log back in for the new environmental variables to take
> effect. If you're on Linux or Mac, verify your PATH contains the folder
> that has VBoxManage in it.

Only way to start the VM is
>  vagrant up --provider=parallels 

But when VM is started with this way, vagrant halt doesn't work with or without the provider.

If you open dokku's Vagrantfile and add 

```
config.vm.provider "parallels" do |prl|
    prl.memory = BOX_MEMORY # 1024
  end
```

Vagrant correctly finds the provider and using ```vagrant up``` or ```vagrant halt``` work as expected. I think if Vagrantfile have predefined providers, it only accepts those ones for the commands. Only ```vagrant up``` command accepts provider flag. Other commands think ```provider=parallels``` as a part of arguments and therefore they refuse to run. 

Just in case, I deleted above block from my Vargantfile, and started vm with 

>  vagrant up --provider=parallels 

Here is the debug log that you requested. https://gist.github.com/tosbaha/3058e81d3d3ac68bb4e9

**Comment by legal90** [comment]
@tosbaha I've reproduced this issue and finally found the reason. It could be also reproduced by running `vagrant status`. Details are in the second part of the message.

#### How to fix it: 
1) The recommended solution - **uninstall VirtualBox correctly**. Seems like you've uninstalled it just by moving `VirtualBox.app` to the Trash, but it's not enough because scripts like `/usr/local/bin/VBoxManage` are still exist. You should open a VirtualBox installation `.dmg` and run `VirtualBox_Uninstall.tool` contained therein.

2) Either you can restore VirtualBox back, or just install it again. In this case `VBoxManage` could be accessible for Vagrant and the error will not be raised.

3) Also this issue could be worked around by this way:
As you've noticed above, you can just add `parallels` provider block to the Vagrantfile. It could be empty, but it's important that it should be defined at the top, _before_ the `virtualbox`:
```ruby
config.vm.provider "parallels"

config.vm.provider "virtualbox" do |vb|
  # something
end
```

#### What actually happens?
In your case there are multiple machines defined in the single Vagrantfile (docs: https://www.vagrantup.com/docs/multi-machine/)

Due to options `autostart: false`, only the machine named "dokku" is creating by `vagrant up` command. But when you run `vagrant halt` or `vagrant suspend`, these commands are applied to all defined machines. For those machines which are not created at the moment, Vagrant tries to detect the default provider. It constructs the list of providers sorted by the priority.

Because of https://github.com/mitchellh/vagrant/commit/ad758bf69a267c8586cee446cf599de2d7cead75 Vagrant considers that providers mentioned in Vagrantfile have a higher priority. The order of mentioning is also important. So, since `:parallels` is not mentioned there, it is in the end of a list.

Then Vagrant checks each provider whether it is usable or not. And that's the place where the error is raised: it detects that `VBoxManage` executable is available by $PATH, but `VBoxManage --version` call fails.
That's why you should either keep VirtualBox working, or uninstall it completely.

I hope it makes sense :-)
