### ISSUE TITLE
After updating to Parallels Desktop 12 Pro I can't start my vagrant maschine

### ISSUE THREAD

**Issue by mediaessenz** [Parallels/vagrant-parallels#272]
I get this error:
```
Vagrant has detected that you have a version of Parallels Desktop for Mac
installed that is not supported. Vagrant Parallels provider is compatible
only with Parallels Desktop 8 or later.

Note: Starting since Parallels Desktop 11 for Mac, Vagrant Parallels
provider can be only used with Pro or Business edition of Parallels
Desktop for Mac. Please, be aware while choosing the edition to upgrade to.
```
I already tried to do `vagrant plugin update vagrant-parallels` but this only returns `All plugins are up to date.`

**Comment by legal90** [comment]
Please, show the output of `vagrant plugin list`

**Comment by mediaessenz** [comment]
vagrant-hostmanager (1.6.1)
vagrant-parallels (1.5.0)
vagrant-share (1.1.5, system)
vagrant-vbguest (0.10.1)

**Comment by mediaessenz** [comment]
after `vargrant plugin install vagrant-parallels` (not *update*) I got this:
vagrant-hostmanager (1.8.5)
vagrant-parallels (1.6.3)
vagrant-share (1.1.5, system)
vagrant-vbguest (0.13.0)

Know starting my vagrant maschine works again.

**Comment by legal90** [comment]
Yes, seems like there is some issue with plugin management in Vagrant. 
In such cases the plugin re-installing should help: `vagrant plugin uninstall <...> && vagrant plugin install <...>`.

I'm closing this issue, because starting since vagrant-parallels `v1.6.0` feature versions of Parallels Desktop should be supported automatically (implemented by GH-229).
