### ISSUE TITLE
Can't get Vagrant to work in Parallels

### ISSUE THREAD

**Issue by gettysburger** [Parallels/vagrant-parallels#288]
I upgraded to Parallels 12 Pro on my Mac because it says it supports Vagrant.

I installed vagrant and VirtualBox like the instructions said but it gave me an error saying I needed VT-x.

So I instead tried Vagrant-Parallels.
Here is what I tried.

vagrant plugin install vagrant-parallels
vagrant add box parallels/ubuntu-14.04
mkdir vagranttest
cd vagranttest
vagrant init parallels/ubuntu-14.04vagrant
vagrant box list (returns parallels/ubuntu-14.04 (parallels, 2.0.4))
vagrant up —provider=parallels  (error: “The provider ‘parallels’ that was requested to back the machine ‘default’ is reporting that it isn’t usable on this system. The reason is shown below: Parallels provider works only on OS X (Mac OS X) systems.’
vagrant up (default: Box Provider: virtualbox)(Erorrs because box does not support virtual box as provider.)

Any thoughts? Thanks.

**Comment by legal90** [comment]
@gettysburger Hm... That looks weird because the OS type is detected on a pretty low level in Vagrant. Are you sure that you run `vagrant up --provider=parallels` on your Mac OS X terminal?

If yes, then please collect the debug output:
```
vagrant up --provider parallels --debug 2>./debug.log
```
It would be better to upload the result `./debug.log` to [Gist](https://gist.github.com/) and provide the link here. Thanks!

**Comment by gettysburger** [comment]
Hi,

It turns out that I did not understand that I was supposed to be running Vagrant on my Mac and not in Parallels. I tried it there and it works. Still makes no sense to me, but it works. Thanks!

-Stephen
