### ISSUE TITLE
Full screen view shows black screen

### ISSUE THREAD

**Issue by dmytro-kaharlytskyi-exa** [Parallels/vagrant-parallels#310]
Hi there,

- OS - macOS 10.13
- Parallels - 10.1.0
- Packer - 1.1.0
- Vagrant - 2.0.0
- vagrant-parallels plugin - 1.7.6

I've build box with packer and when I start vagrant,
it works fine with default screen resolution - http://prntscr.com/gxanux
but when I switch to full screen it's just black - http://prntscr.com/gxao6r
However, RDP works fine with big resolution.

**Comment by legal90** [comment]
I'm pretty sure that this problem is caused by the compatibility issue between Parallels Tools installed in the VM (derived from a box) and the host part of Parallels Desktop - 10.1.0 was already too old in Oct 2017.

The list of versions reached their End-Of-Life could be found here: https://kb.parallels.com/en/123560

I understand that my reply is too late most likely. But if the issue still affect you on the actual version of Parallels Desktop, please create a new GitHub issue.
