### ISSUE TITLE
Encrypted parallels VM

### ISSUE THREAD

**Issue by gavD** [Parallels/vagrant-parallels#317]
I am using vagrant-parallels and would like to encrypt my VM. I ran `vagrant up`, then in Parallels, encrypted my VM.

Subsequent to this, I was unable to `vagrant up` or `vagrant provision` as it prompts for a password.

```
$ vagrant up
Bringing machine 'foobar' up with 'parallels' provider...
==> foobar: Checking if box 'bento/ubuntu-14.04' is up to date...
Virtual machine 'foobar_123' is encrypted - password required to continue operation
Please enter password: d
```

Is there any way around this? Can I supply the encryption password as an environment variable or similar?

Thanks,
- Gavin

**Comment by legal90** [comment]
@gavD Thank's for filing this issue!
We need to do some work on the provider in order to handle these password prompts and pass them through vagrant CLI.

But before that, I want to figure out something about the `prlctl` behavior.
As I can see, `prlctl` utility asks for a password almost on every action.  Some of them look a bit confusing, for example:
- `prlctl enter`
- `prlctl exec`
- `prlctl capture`
These actions are supposed to be executed against the running VM, so it should be already decrypted. There should be no need for asking a password again.

- `prlctl set`
As I understand, the "VM encryption" feature in Parallels Desktop implies the virtual disk encryption. Then it weird password is required for changing the configuration file, which is actually not encrypted (`config.pvs`).

@romankulikov Do you know - is it a bug, or an intendant behavior?

Considering that prlctl doesn't support sessions and don't memorize the password, we might have too many subsequent password prompts in some Vagrant use cases.

**Comment by legal90** [comment]
Pinging @alevlasu @romankulikov 
Do you guys know - is there a real reason for asking a decryption password for `enter`, `exec`, `capture` and `set` command of `prlctl`? Or it will be removed?

Currently it doesn't look reasonable to implement a support of encrypted VMs in this provider, because it will cause dozens of password prompts for a single `vagrant up` run.

**Comment by romankulikov** [comment]
It is an intentional behaviour.

I'm not sure if its worth using VM encryption at all in vagrant-related environments. May be file system encryption by own means of guest OS is a more suitable thing here.

**Comment by legal90** [comment]
We should state that the "VM encryption" feature of Parallels Desktop is not supported by this vagrant provider and there are no plans to have it implemented. 

I'm closing this issue.
