### ISSUE TITLE
Vagrant unable to ssh to guest

### ISSUE THREAD

**Issue by Ezsra-McDonald** [Parallels/vagrant-parallels#342]
I am new to Parallels. I have been using Vagrant with VirtualBox. This week I purchased a copy of Parallels Desktop 15 for Business.

First thing I did was install the plugin
$ vagrant plugin install vagrant-parallels

Next I tried creating a centos7 guest.
$ mkdir centos7p
$ cd centos7p
$ vagrant init "generic/centos7"
$ vagrant up --provider=parallels

The box begins to load and finally I see the following:
==> default: Registering VM image from the base box 'generic/centos7'...
==> default: Creating new virtual machine as a linked clone of the box image...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'generic/centos7' version '1.9.28' is up to date...
==> default: Setting the name of the VM: centos7p_default_1568126911696_44025
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
.......
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.14:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...

I checked the SSH configuration:
$ vagrant ssh-config
Host default
  HostName 10.211.55.15
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/somewhere/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

This is not what I am used to. Normally, vagrant used a port forward. So I checked and can not access port 22 on 10.211.55.15. SSH is running and no firewall is enabled.

I tried other Boxes. They all do the same thing, Ubuntu, Centos, does not seem to matter.

I googled around for a while and did not find a solution. Any assistance would be appreciated.

:Ez

**Comment by romankulikov** [comment]
Port forwarding means (in your case) that guest port 22 is mapped to host port 2200. In other words SSH should work on VM's port 22. The question is why guest's port 22 is not accessible. Do still suffer this issue?

**Comment by legal90** [comment]
@Ezsra-McDonald The default Vagrant provider `virtualbox` uses port forwarding for SSH.
But `parallels` provider uses the connection by the VMs private IP instead. In your case it's `10.211.55.15 `.

Since you are saying that the issue happens on all boxes, I would guess that you could have a network collision between one of the network interfaces on your computer (like VPN, WiFi or Ethernet) and the private network from Parallels Desktop called "Shared".
By default "Shared" network in Parallels Desktop uses the range `10.211.55.1 - 10.211.55.254`. If it overlaps with other connection, try changing it as described here:
https://download.parallels.com/desktop/v15/docs/en_US/Parallels%20Desktop%20User's%20Guide/43111.htm

**Comment by legal90** [comment]
I'm going to close this issue now. Feel free to create a new on if you still have this problem.
