### ISSUE TITLE
Problem with initialization vagrant image (macOS)

### ISSUE THREAD

**Issue by dukebarman** [Parallels/vagrant-parallels#344]
I had early installed vagrant with vbox. But replaced VirtualBox (deleted it) by parallels. After upgrade vagrant and install parallels plugin I couldn't init vagrant image.

```
# vagrant init bento/ubuntu-18.04
Vagrant failed to initialize at a very early stage:

The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

If you're on Windows and just installed VirtualBox, you have to
log out and log back in for the new environmental variables to take
effect. If you're on Linux or Mac, verify your PATH contains the folder
that has VBoxManage in it.
```

I've tried advice from another issue `vagrant destroy -f` but it doesn't help.

Testing: macOS 10.14.6

**Comment by dukebarman** [comment]
Same error after reinstall vagrant-parallels and init

**Comment by legal90** [comment]
It seems that vagrant fails to initialize plugins, so it doesn't detect that `parallels` provider is installed and then falls back to the default `virtualbox`.

I found some similar issues filed for recent Vagrant versions:
https://github.com/hashicorp/vagrant/issues/11058
https://github.com/hashicorp/vagrant/issues/11156

I can't reproduce this issue on my machine with Vagrant v2.2.6, macOS 10.15.
Since it's out of the scope of the provider, I would recommend filing an issue in Vagrant repo instead (https://github.com/hashicorp/vagrant/issues/)

Otherwise I can only suggest:
- try running `vagrant plugin expunge --reinstall` and see if it helps
- OR delete `~/.vagrant.d` and install the plugin again. That will delete all plugins and cached boxes.
- OR reinstall Vagrant completely (https://www.vagrantup.com/docs/installation/uninstallation.html), with deleting `~/.vagrant.d`

**Comment by dukebarman** [comment]
Last 3 options don't help :(

**Comment by dukebarman** [comment]
I reuninstall virtualbox and problem was disappeared.
