### ISSUE TITLE
Customization: 'natdnshostresolver'  option

### ISSUE THREAD

**Issue by dkushnikov** [Parallels/vagrant-parallels#97]
В virtualbox имеется возможность включить флаг natdnshostresolver

```
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
```

Он в том числе позволяет обращаться с гостевой машины к адресам, которые прописаны в файле /etc/hosts хоста.
При использовании parallels-адаптера выдается ошибка. 

```
#<VagrantPlugins::Parallels::Errors::PrlCtlError: There was an error while executing `prlctl`, a CLI used by Vagrant
for controlling Parallels Desktop. The command and stderr is shown below.
```

Есть ли какой-то флаг, которые позволяет сделать аналогичные вещи?

**Comment by bassamtabbara** [comment]
I believe we need an equivalent of "natdnshostresolver1" in parallels. Without it every guest VM would have to be modified to add an option to /etc/resolv.conf. On some guests (like CoreOS) where systems-resolved manages /etc/resolv.conf this is not trivial to do. 

Why was this issue closed?

**Comment by ericrini** [comment]
+1 for supporting this

**Comment by bassamtabbara** [comment]
@legal90 and parallels team, what is the status on this issue? It still doesn't work on Parallels 11 Desktop Business edition. The DNS resolution is extremely slow without "options single-request-reopen" and its not an option to modify /etc/resolv.conf on many hosts (especially CoreOS).

**Comment by bassamtabbara** [comment]
I've narrowed the issue a little more. 

I have the following setup. My host machine OSX El Capitan as the following in its /etc/resolv.conf:

```
nameserver 192.168.0.1
nameserver 2001:558:feed::1
nameserver 2001:558:feed::2
```

When I boot a modern Linux guest machine (such as CoreOS) and use Shared Networking with default settings in Parallels (DHCP v4 and v6 enabled), DNS resolution fails on the guest. For example:

```
core@coreos01 ~ $ curl http://www.parallels.com 
curl: (6) Couldn't resolve host 'www.parallels.com'
```

I can workaround this in two ways:
  1) turn off IPv6 on the host
  2) add the following to /etc/resolv.conf on the guest "option single-request-reopen"

Both of these are workaround and the real problem seems to be in the DNS implementation inside Parallels Desktop. This problem does not happen on VMWare Fusion, nor Virtualbox.

**Comment by legal90** [comment]
The subject feature was implemented in Parallels Desktop 11. 
The feature is enabled by default for all VMs with Shared network adapter and it works similarly to `natdnshostresolver1 on` in VirtualBox: guests could resolve domain addresses which are specified in `/etc/hosts` on the host machine.

But seems like the issue you are talking about is related to #138 rather than this one. 
I'll reopen it, so let's continue the discussion there.
